openapi: 3.0.0
info:
  title: "Blog Application"
  version: "fileVersion"

servers:
  - url: http://localhost:{port}/api/articles/{version}
    variables:
      version:
        default: 'v1'
      port:
        default: '8080'

paths:

  /articles:
    post:
      tags:
        - "articles"
      summary: "Add a new article to the App"
      description: ""
      parameters:
        - in: "header"
          name: "body"
          description: "Article to add"
          required: true
          schema:
            $ref: '#/components/schemas/ArticleDto'
      responses:
        '201':
          description: Article Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ArticleDto'

    get:
      tags:
        - "articles"
      summary: Get all articles
      responses:
        '200':
          description: A list of articles.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticleDto'

  /articles/{articleId}:
    get:
      tags:
        - "articles"
      summary: Get an Article
      description: Returns an article for givenn id
      parameters:
        - in: path
          name: articleId
          required: true
          schema:
            type: string
          description: Articles Id

      responses:
        '200':
          description: 'Returned Correctly'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/ArticleDto'
        '500':
          description: "Internal error"

        '404':
          description: 'Article not found'
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/CustomError'

  /users:
    post:
      tags:
        - "users"
      summary: "Add a new author to the App"
      description: ""
      parameters:
        - in: "header"
          name: "body"
          description: "User to add"
          required: true
          schema:
            $ref: '#/components/schemas/Author'
      responses:
        '201':
          description: Article Created.
          content:
            application/vnd.api+json:
              schema:
                $ref: '#/components/schemas/Author'

    get:
      tags:
        - "users"
      summary: Get all users
      responses:
        '200':
          description: A list of users.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ArticleDto'


components:
  schemas:
    CustomError:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - status
        - message

    Author:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            name:
              type: string
          required:
            - name
      required:
        - id
        - type
        - attributes

    ArticleDto:
      type: object
      properties:
        id:
          type: string
        type:
          type: string
        attributes:
          type: object
          properties:
            title:
              type: string
            body:
              type: string
            author:
              $ref: '#/components/schemas/Author'

          required:
            - title
            - body
            - author
        relationships:
          type: object
          properties:
            comments:
              type: object
              properties:
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      type:
                        type: string
              required:
                - id
                - type
      required:
        - id
        - type
        - attributes
        - relationships